# Generated by Django 3.2.5 on 2022-04-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='photos/default.png', upload_to='photos/'),
        ),
    ]
